application: tweets-notifier
version: 1
runtime: php56
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?composer\.(phar|lock|json)$

handlers:
- url: /css
  static_dir: webroot/css

- url: /js
  static_dir: webroot/img

- url: /img
  static_dir: webroot/img

- url: /favicon.ico
  static_files: webroot/favicon.ico
  upload: webroot/favicon.ico

- url: /.*
  script: webroot/index.php